export const sectionName = [
    "Nagpur to Ballarshah",
    "Nagpur to Wardha",
    "Nagpur to Betul",
    "Nagpur to Chandrapur",
    "Nagpur to Sewagram", 
    "Nagpur to Ajni",
    "Nagpur to Amla",
    "Nagpur to Bhandak",
    "Nagpur to Bhugaon",
    "Nagpur to Chandur",
    "Nagpur to Dhamangaon",
    "Nagpur to Ghoradongri",
    "Nagpur to Hinganghat",
    "Nagpur to Junnardeo",
    "Nagpur to Katol",
    "Nagpur to Multai",
    "Nagpur to Narkhed",
    "Nagpur to Pandhurna",
    "Nagpur to Parasia",
    "Nagpur to Pulgaon",
    "Nagpur to Warora",
    "Nagpur to Babupeth",
    "Nagpur to Barbatpur",
    "Nagpur to Barsali",
    "Nagpur to Bharatwada",
    "Nagpur to Bordhai",
    "Nagpur to Borkhedi",
    "Nagpur to Butibori",
    "Nagpur to Chichonda",
    "Nagpur to Chikni Road",
    "Nagpur to Dahegaon",
    "Nagpur to Dharakhoh",
    "Nagpur to Dhodramohor",
    "Nagpur to Godhni",
    "Nagpur to Gumgaon",
    "Nagpur to Hirdagarh",
    "Nagpur to Iklehra",
    "Nagpur to Jambhara",
    "Nagpur to Jaulkheda",
    "Nagpur to Kalaakhar",
    "Nagpur to Kalambha",
    "Nagpur to Kalmeshwar",
    "Nagpur to Kaotha",
    "Nagpur to Kayar",
    "Nagpur to Khapri",
    "Nagpur to Kirathgarh",
    "Nagpur to Kohli",
    "Nagpur to Lingti",
    "Nagpur to Majri",
    "Nagpur to Majri Khadan",
    "Nagpur to Malkhed",
    "Nagpur to Maramjhiri",
    "Nagpur to Metpanjra",
    "Nagpur to Morshi",
    "Nagpur to Nagri",
    "Nagpur to Navegaon",
    "Nagpur to Palachauri",
    "Nagpur to Pimpalkhuti",
    "Nagpur to Pusla",
    "Nagpur to Saheli",
    "Nagpur to Seloo Road",
    "Nagpur to Sindi",
    "Nagpur to Sonegaon",
    "Nagpur to Sonkhamb",
    "Nagpur to Tadali",
    "Nagpur to Taku",
    "Nagpur to Talni",
    "Nagpur to Teegaon",
    "Nagpur to Timtala",
    "Nagpur to Tuljapur",
    "Nagpur to Wagholi",
    "Nagpur to Wani",
    "Nagpur to Warud Orange City",
    "Nagpur to Kalamb",
    "Nagpur to Deoli",
    "Nagpur to Barchi Road",
    "Nagpur to Barelipar",
    "Nagpur to Benoda",
    "Nagpur to Gangiwara",
    "Nagpur to Markadhana",
    "Nagpur to Mowad",
    "Nagpur to Varud",
    "Nagpur to Darimeta",
    "Nagpur to Ghudankhapa",
    "Nagpur to Gondwana Visapur",
    "Nagpur to Hatnapur",
    "Nagpur to Lalawadi",
    "Nagpur to Magrdoh",
    "Nagpur to Malkapur  Road",
    "Nagpur to Tinkheda",
    "Nagpur to Bhidi",
    "Nagpur to Riddhapur",
  ];